FROM openjdk:8

ADD install.sh .
ADD yices yices-sat yices-smt yices-smt2 z3 cvc3 cvc4 /usr/bin/

RUN set -o errexit -o nounset \
    && apt-get update -y \
    && apt-get install -y findutils git wget curl python3-requests unzip zip

RUN install.sh

RUN set -o errexit -o nounset \
        && echo "Testing Gradle installation" \
        && java -version \
        && gradle --version
