FROM fedora:29

ADD yices yices-sat yices-smt yices-smt2 z3 cvc3 cvc4 /usr/bin/

RUN set -o errexit -o nounset \
    && dnf update -y \
    && dnf install -y findutils git wget curl python3-requests unzip zip java-11-openjdk-devel gradle

RUN set -o errexit -o nounset \
        && echo "Testing Gradle installation" \
        && java -version\
        && gradle --version
