FROM python

RUN pip install  mkdocs  mkdocs-material  pymdown-extensions pygments markdown-blockdiag markdown-aafigure==v201904.0002

RUN which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
RUN which rsync     || ( apt-get update -y && apt-get install -y rsync)
